extends: spectral:oas

rules:
  no-delete-accounts::
    description: FELETE operations on accounts are not permitted
    severity: error
    given: "$.paths[*].delete"
    then:
      function: falsy

